### ISSUE TITLE
Image field overlaps other controls.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudBook/EasyCloudBooks#7]
After uploading some image(mostly portrait), Image control overlaps next control.

![screenshot from 2019-01-21 15-46-50](https://user-images.githubusercontent.com/46882833/51468331-b0cb7580-1d94-11e9-8068-cb800df57a89.png)

**Comment by mitulpanch** [comment]
Solved

**Comment by risipatel** [comment]
Company page has same issue.
